// ⚠️ 자동 생성 파일 — 직접 수정하지 말 것.
// scripts/generateAssetManifest.mjs 가 public/ 을 훑어 만든다 (npm run gen:assets).
// public/ 에 사운드나 이미지를 추가/삭제한 뒤 dev/build를 다시 돌리면 갱신된다.

export type SfxName = 'sheep' | 'mermaid' | 'tiger' | 'rabbit' | 'card' | 'bomb';

/** 효과음 — 접두사별 파일 목록(같은 접두사 안에서 무작위로 하나 재생) */
export const SFX_MANIFEST: Record<SfxName, string[]> = {
  "sheep": [
    "/sounds/sheep_1.mp3",
    "/sounds/sheep_2.mp3",
    "/sounds/sheep_3.mp3",
    "/sounds/sheep_4.mp3",
    "/sounds/sheep_5.mp3",
    "/sounds/sheep_6.mp3"
  ],
  "mermaid": [
    "/sounds/mermaid_1.mp3",
    "/sounds/mermaid_2.mp3",
    "/sounds/mermaid_3.mp3"
  ],
  "tiger": [
    "/sounds/tiger_1.mp3",
    "/sounds/tiger_2.mp3",
    "/sounds/tiger_3.mp3"
  ],
  "rabbit": [
    "/sounds/rabbit_1.mp3",
    "/sounds/rabbit_2.mp3",
    "/sounds/rabbit_3.mp3",
    "/sounds/rabbit_4.mp3",
    "/sounds/rabbit_5.mp3"
  ],
  "card": [
    "/sounds/card_1.mp3",
    "/sounds/card_2.mp3"
  ],
  "bomb": [
    "/sounds/bomb.wav"
  ]
};

/** 배경음악 — 용량이 커서 프리로드하지 않고 재생 시 스트리밍한다. */
export const BGM_FILES: string[] = [
  "/sounds/bgm_game1.mp3",
  "/sounds/bgm_game2.mp3",
  "/sounds/bgm_main.mp3",
  "/sounds/bgm_opening.mp3"
];

/** 게임 시작 전에 미리 받아둘 이미지 */
export const IMAGE_FILES: string[] = [
  "/places/dock.png",
  "/places/dock_text.png",
  "/places/forest_road.png",
  "/places/forest_road_text.png",
  "/places/house.png",
  "/places/house_text.png",
  "/places/river_road.png",
  "/places/river_road_text.png",
  "/skills/mermaid_skill.png",
  "/skills/rabbit_skill.png",
  "/skills/sheep_skill.png",
  "/skills/tiger_skill.png",
  "/emoticon/mermaid_burn.png",
  "/emoticon/mermaid_cry.png",
  "/emoticon/mermaid_focus.png",
  "/emoticon/mermaid_happy.png",
  "/emoticon/mermaid_stone.png",
  "/emoticon/rabbit_burn.png",
  "/emoticon/rabbit_cry.png",
  "/emoticon/rabbit_focus.png",
  "/emoticon/rabbit_happy.png",
  "/emoticon/rabbit_stone.png",
  "/emoticon/sheep_burn.png",
  "/emoticon/sheep_cry.png",
  "/emoticon/sheep_focus.png",
  "/emoticon/sheep_happy.png",
  "/emoticon/sheep_stone.png",
  "/emoticon/tiger_burn.png",
  "/emoticon/tiger_cry.png",
  "/emoticon/tiger_focus.png",
  "/emoticon/tiger_happy.png",
  "/emoticon/tiger_stone.png",
  "/howto/how_IPs.png",
  "/howto/how_places.png",
  "/howto/how_skills.png",
  "/lobby/loading_bg.webp",
  "/lobby/logo.png",
  "/lobby/panel_create.webp",
  "/lobby/panel_join.webp",
  "/lobby/panel_multi.webp",
  "/lobby/panel_solo.webp",
  "/lobby/table_bg.webp",
  "/ui/back_board.png",
  "/ui/btn_dice.webp",
  "/ui/btn_plank.webp",
  "/ui/btn_random.webp",
  "/ui/btn_solo_bar.webp",
  "/ui/btn_spectator.webp",
  "/ui/btn_start_bar.webp",
  "/ui/btn_team_a.webp",
  "/ui/btn_team_b.webp",
  "/ui/button_bg.webp",
  "/ui/corner_bl.webp",
  "/ui/corner_br.webp",
  "/ui/corner_tl.webp",
  "/ui/corner_tr.webp",
  "/ui/hand_mermaid.webp",
  "/ui/hand_rabbit.webp",
  "/ui/hand_sheep.webp",
  "/ui/hand_tiger.webp",
  "/ui/howto_board.webp",
  "/ui/howto_corner_bl.webp",
  "/ui/howto_corner_br.webp",
  "/ui/howto_corner_tl.webp",
  "/ui/howto_corner_tr.webp",
  "/ui/howto_title.webp",
  "/ui/icon_cog.webp",
  "/ui/icon_create.webp",
  "/ui/icon_help.webp",
  "/ui/icon_rank.webp",
  "/ui/icon_start.webp",
  "/ui/input_box.webp",
  "/ui/laurel_book.webp",
  "/ui/medal_1.webp",
  "/ui/medal_2.webp",
  "/ui/score_board.webp",
  "/play/acorn_bar.webp",
  "/play/arrow_green.webp",
  "/play/arrow_wood.webp",
  "/play/badge_crown.webp",
  "/play/bar_dark.webp",
  "/play/bar_light.webp",
  "/play/bar_sm.webp",
  "/play/beam.webp",
  "/play/board_h.webp",
  "/play/board_sq.webp",
  "/play/board_v.webp",
  "/play/card_corner_bl.webp",
  "/play/card_corner_br.webp",
  "/play/card_corner_tl.webp",
  "/play/card_corner_tr.webp",
  "/play/card_frame.webp",
  "/play/card_plaque.webp",
  "/play/decor_bush.webp",
  "/play/decor_cattail.webp",
  "/play/decor_grass.webp",
  "/play/decor_log.webp",
  "/play/decor_mushroom.webp",
  "/play/decor_stones.webp",
  "/play/decor_stump.webp",
  "/play/gauge.webp",
  "/play/gauge_fill.webp",
  "/play/gauge_track.webp",
  "/play/icon_acorn.webp",
  "/play/icon_cog.webp",
  "/play/icon_lock.webp",
  "/play/label_small.webp",
  "/play/leaf_decal_1.webp",
  "/play/leaf_decal_2.webp",
  "/play/leaf_decal_3.webp",
  "/play/leaf_decal_4.webp",
  "/play/log_bar.webp",
  "/play/nameplate.webp",
  "/play/note_green.webp",
  "/play/note_green_rows.webp",
  "/play/note_pink.webp",
  "/play/note_pink_rows.webp",
  "/play/pg_bar_lg.webp",
  "/play/pg_bar_md.webp",
  "/play/pg_bar_sm.webp",
  "/play/pg_card.webp",
  "/play/pg_square.webp",
  "/play/pg_strip.webp",
  "/play/pill_gold.webp",
  "/play/pill_green.webp",
  "/play/pill_leaf.webp",
  "/play/pill_sm_gold.webp",
  "/play/pill_sm_green.webp",
  "/play/pill_sm_wood.webp",
  "/play/pill_wood.webp",
  "/play/plank.webp",
  "/play/play_bg.webp",
  "/play/wf_bar_lg.webp",
  "/play/wf_bar_md.webp",
  "/play/wf_card.webp",
  "/play/wf_plaque.webp",
  "/play/wf_square.webp",
  "/play/wf_strip.webp"
];

/** 프리로드 대상 전체(효과음 + 이미지) */
export const PRELOAD_FILES: string[] = [
  ...Object.values(SFX_MANIFEST).flat(),
  ...IMAGE_FILES,
];
